# Generated by Django 4.0.3 on 2022-03-28 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_newsletterrecipients_alter_article_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletterrecipients',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
