# Generated by Django 4.0.3 on 2022-03-28 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_newsletterrecipients_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsletterrecipients',
            name='email',
        ),
        migrations.RemoveField(
            model_name='newsletterrecipients',
            name='name',
        ),
    ]
